<?php

abstract class Notify{
    protected $credit_num = 15;
    abstract public function content();
    public  function message(){
        return '<span style="color: chartreuse">'.$this->content().'奖励'.$this->credit().'个积分</span>';
    }

    public function credit(){
        return $this->credit_num;
    }


}


class User extends Notify{

    protected $credit_num=10;

    public function usemessage()
    {
        return 'hello.how are u'; // TODO: Change the autogenerated stub
    }



    public function login(){
        return $this->message();
    }

    public function register(){
        return $this->message();
    }

    public function message()
    {
        echo "保存到数据库,这是在发送消息之前所做的工作";
        return parent::message(); // TODO: Change the autogenerated stub
    }

    public function credit()
    {
        return $this->credit_num; // TODO: Change the autogenerated stub
    }

    public function content()
    {
        return '中国666';
        // TODO: Implement content() method.
    }


}

class Comment extends Notify{
    public function send(){
        return $this->message();
    }

    public function content()
    {
        return '中国666,中国牛叉威武';
        // TODO: Implement content() method.
    }


}

//echo (new Comment())->send();

echo '<hr/>';

echo (new User)->login();